apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: lpxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lpxy
    app.kubernetes.io/part-of: byoc-app-rwrb
  name: lpxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: lpxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: lpxy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-uqwc-tenant/byoc-app-rwrb/lpxy@sha256:1eec5c790d26ec82b9df32687dec8c6f210cb433f61f11dd7ad3cd4a813be089
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
